version: '3.9'

services:
  db:
    image: postgres:15
    container_name: jobqueue_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jobqueue
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: jobqueue_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/jobqueue
    volumes:
      - .:/app

volumes:
  postgres_data:
