version: '3.9'

services:
  db:
    image: postgres:15
    container_name: jobqueue_db
    restart: always
    environment:
      POSTGRES_DB: jobs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d  # Run SQL on first boot

volumes:
  postgres_data:


  web:
    build: .
    container_name: jobqueue_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    volumes:
      - .:/app
