services:
  db:
    image: postgres:15
    container_name: jobqueue_db
    restart: always
    environment:
      POSTGRES_DB: jobs_db         # ✅ custom database name
      POSTGRES_USER: POSTGRES_PASSWORD       # ✅ custom user
      POSTGRES_PASSWORD: postgres@123  # ✅ custom password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: jobqueue_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://jobuser:jobpass@123@db:5432/jobs_db  # ✅ use new credentials
    volumes:
      - .:/app

volumes:
  postgres_data:
